### ISSUE TITLE
Regression: taobao mirror does not have v in directory path

### ISSUE THREAD

**Issue by umbrella22** [electron/get#120]
when i use mirror site
it seems that @electron/get request the wrong url:
`https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip`
in 6.1.2
` https://npm.taobao.org/mirrors/electron/6.1.2/electron-v6.1.2-darwin-x64.zip `
it not strip 'v' from version number in the dir part .

so different behavior for electron-download from @electron/get package

[The specific information is here](https://github.com/electron/electron/issues/20739#issuecomment-546568300)

**Comment by flyxlee** [comment]
when I install in raspberry pi, I meet the same problem，have it solved？ @malept

**Comment by flyxlee** [comment]
> when I install in raspberry pi, I meet the same problem，have it solved？ @malept

@MarshallOfSound  we the code by version 7.1.2,it likes 
![image](https://user-images.githubusercontent.com/10684063/69856193-0bdccb80-12c8-11ea-87fb-b70851bbfe31.png)

**Comment by nickfan** [comment]
update:
it's fixed now.

change url to:
```
electron_mirror=https://cdn.npm.taobao.org/dist/electron
```

from:

https://github.com/cnpm/cnpmjs.org/issues/1530#issuecomment-561081645

**Comment by umbrella22** [comment]
@nickfan  After setting it to this, development is normal; but when executing the build command, I get 404 error as shown in the figure
![404](https://user-images.githubusercontent.com/19886152/70118129-449eeb00-16a2-11ea-9db0-75609138154b.png)

**Comment by nickfan** [comment]
> @nickfan After setting it to this, development is normal; but when executing the build command, I get 404 error as shown in the figure
> ![404](https://user-images.githubusercontent.com/19886152/70118129-449eeb00-16a2-11ea-9db0-75609138154b.png)

maybe add the last slash

```sh
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
```

**Comment by CharonTao** [comment]
Which version will fix this

**Comment by malept** [comment]
The workaround is to use the CDN version of the taobao mirror, as documented in the [Installing Electron guide](https://www.electronjs.org/docs/tutorial/installation#mirror) and in the comments above.
