### ISSUE TITLE
Windows Error: "EPERM: operation not permitted, lstat"

### ISSUE THREAD

**Issue by aruntech89** [electron/get#122]
Dear All,

We are trying to package our electron application for win32 platform .

**Steps that we have already followed:**

1) Using electron-packager we tried to build the .exe file of our application but we  ran into the lstat error.

so I have logged the issue under electron-packager
https://github.com/electron/electron-packager/issues/1064

**Form there I was advised to download the binary files using electron/get**
2) We downloaded the electron/get module and tried running the simple js file to download binary files 
**but facing the same issue :**
Error:  EPERM: operation not permitted, lstat 'C:\Users\arun\AppData\Local\Temp\electron-download-nY2x6M\electron-v6.0.7-win32-x64.zip'

Even after setting cache folder as electon_cache=C:\Users\ath6cob\AppData\Local\electron\Cache in environment variable the download creates random temp folder whenever i run the command.

I am a beginner but it is really becoming difficult to build an exe file. 

Please advise 

`Arun

**Comment by craxal** [comment]
I've had the same problem. I'm using @electron/get directly.

**Comment by aruntech89** [comment]
Any input please advise.

**Comment by ivysrono** [comment]
+1

**Comment by craxal** [comment]
So, I only get this issue on Windows. On a Mac, I get a 404 error. May be related to #125? Now that I know my error was really a 404, I managed to resolve after double-checking a few variables in some scripts for `undefined`. 🤦‍♂️

**Comment by siaikin** [comment]
look at [this](https://github.com/electron/get/issues/124#issuecomment-549157747) and #123 , hope this felpful.

**Comment by youyinnn** [comment]
+1 i am so depressed because of this problem

**Comment by aruntech89** [comment]
1) Pointed to local mirror and tried building failing in checksum and also
2 )I tried with Admin privilege and still facing the same issue in Windows10

For users behind proxy and in corporate network, Are we missing any parameter or configuration  ?

Kindly advise 

Arun

**Comment by youyinnn** [comment]
maybe is something related to your anti-virus application in your machine, try to turn off them and build again?

**Comment by crazafimahatratra** [comment]
The same issue for me on windows.
Works with 
`npm i -D electron-nightly`

**Comment by ZhoDi** [comment]
I had the same problem.Not even the administrator.
At first, I solved him by `cnpm install -g electron`
Finally find
Alter File ~/.npmrc
Add a line `electron_mirror=https://cdn.npm.taobao.org/dist/electron/`

**Comment by ivysrono** [comment]
@ZhoDi Great, thanks.

**Comment by liudonghua123** [comment]
> I had the same problem.Not even the administrator.
> At first, I solved him by `cnpm install -g electron`
> Finally find
> Alter File ~/.npmrc
> Add a line `electron_mirror=https://cdn.npm.taobao.org/dist/electron/`

@ZhoDi Thanks for your tips, it worked for me!

**Comment by malept** [comment]
As of `@electron/get` version 1.7.5, the lstat error should not be showing up anymore.
