### ISSUE TITLE
about mirrorOption version(x.x.x -> vx.x.x)

### ISSUE THREAD

**Issue by siaikin** [electron/get#123]
[commit code](https://github.com/electron/get/commit/76c41479e2369ff62b254c01dac42920459845fa#diff-e1495d267619047a7cca5cfe8f692729R27)

i use this mirror 'https://npm.taobao.org/mirrors/electron/' in china.

in 7.0.0 '@electron/get' request wrong url:
'https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip'

but in 6.1.2 request this url:
'https://npm.taobao.org/mirrors/electron/6.1.2/electron-v6.1.2-darwin-x64.zip'

i seems in this [code](https://github.com/electron/get/commit/76c41479e2369ff62b254c01dac42920459845fa#diff-e1495d267619047a7cca5cfe8f692729R27) you sue `v${version}`. this should be the cause.

ps thanks @nickfan

**Comment by wells1013** [comment]
+1

**Comment by chanble** [comment]
taobao mirror is update https://github.com/cnpm/cnpmjs.org/issues/1551#issuecomment-586829084
