### ISSUE TITLE
Global binary is missing

### ISSUE THREAD

**Issue by liudonghua123** [electron/get#142]
I used `electron-download` a lot, but now when I use this utility to download electron to local cache, I always failed with the error shown on https://github.com/electron/get/issues/122. I go through the code, find the cache location changed from `%LOCALAPPDATA%/electron/Cache` to `%LOCALAPPDATA%/electron/Cache/httpnpm.taobao.orgmirrorselectronv8.0.0electron-v8.0.0-win32-x64.zip`.  For this change, I could not use `electron-download` to download electron from mirror especially from China, and install electron via the local cache from `electron-download`.
I found the repository changed from https://github.com/electron-userland/electron-download to https://github.com/electron/get. 
Can we provide a binary for downloading electron to local cache like .`electron-download` did?

**Comment by malept** [comment]
There are no plans to (re-)add a CLI tool.
