### ISSUE TITLE
404 error when downloading electron

### ISSUE THREAD

**Issue by kaosnoff** [electron/get#150]
The Taobao mirror (npm.taobao.org) dropped the "v" on the version part of the address (customDir).

Instead of:
https://npm.taobao.org/mirrors/electron/v8.0.1/electron-v8.0.1-win32-x64.zip

The adddress now is:
https://npm.taobao.org/mirrors/electron/8.0.1/electron-v8.0.1-win32-x64.zip

This leads to 404 errors every time someone uses the Taobao mirror (apparently the default one now).

**Comment by malept** [comment]
This is an issue on the taobao end, not `@electron/get`. The way to access the taobao mirror is documented on the Electron website: https://www.electronjs.org/docs/tutorial/installation#mirror

**Comment by kaosnoff** [comment]
Temp fix by changing the file at: node_modules/@electron/get/dist/cjs/artifact-utils.js: 33 to:
`
function getArtifactRemoteURL(details) {
    const opts = details.mirrorOptions || {};
    let base = mirrorVar('mirror', opts, BASE_URL);
    if (details.version.includes('nightly')) {
        base = mirrorVar('nightly_mirror', opts, NIGHTLY_BASE_URL);
    }
    var path = mirrorVar('customDir', opts, details.version).replace('{{ version }}', details.version.replace(/^v/, ''));
		path = path.replace('v', '');
    const file = mirrorVar('customFilename', opts, getArtifactFileName(details));
    return `${base}${path}/${file}`;
}
`

The fix sugested by @malept doesn't work. I really don't want to access the taobao mirror, it's the DEFAULT option now, but it is getting the wrong address AFTER the URL informed (more precisely on the {{version}} folder).

**Comment by malept** [comment]
To be clear, if setting the following environment variables (this is directly from the documentation that I linked in my earlier comment) does not work, it's a bug:

```
ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
ELECTRON_CUSTOM_DIR="{{ version }}"
```

**Comment by kaosnoff** [comment]
Yes, it is a bug. That's why I oppened an issue here.

**Comment by malept** [comment]
In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you try to download Electron with the environment variable `DEBUG=@electron/get:*` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What environment variables and/or NPM config are you setting exactly?

* Please provide detailed steps to reproduce your problem.

**Comment by kaosnoff** [comment]
Info & steps to reproduce:

- Operational System: Windows 10 Enterprise

- Console output:
`C:\dev\testes\electron\bugtest>set DEBUG=@electron/get:* & npm install electron --save-dev

> core-js@3.6.4 postinstall C:\dev\testes\electron\bugtest\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@8.1.1 postinstall C:\dev\testes\electron\bugtest\node_modules\electron
> node install.js

  @electron/get:index Checking the cache (undefined) for electron-v8.1.1-win32-x64.zip (https://npm.taobao.org/mirrors/electron/v8.1.1/electron-v8.1.1-win32-x64.zip) +0ms
  @electron/get:index Cache miss +9ms
  @electron/get:index Downloading https://npm.taobao.org/mirrors/electron/v8.1.1/electron-v8.1.1-win32-x64.zip to D:\Users\dfreire\AppData\Local\Temp\electron-download-sSJc1v\electron-v8.1.1-win32-x64.zip with options: undefined +74ms
(node:23220) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.1.1/electron-v8.1.1-win32-x64.zip
    at EventEmitter.emitter.on.response (C:\dev\testes\electron\bugtest\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (events.js:198:13)
    at module.exports (C:\dev\testes\electron\bugtest\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (C:\dev\testes\electron\bugtest\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args [as emit] (C:\dev\testes\electron\bugtest\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
(node:23220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bugtest@1.0.0 No description
npm WARN bugtest@1.0.0 No repository field.

+ electron@8.1.1
added 86 packages from 96 contributors and audited 103 packages in 35.71s
found 0 vulnerabilities`

- No ENV variables, these are the NPM config (although the only manual settings I've made so far were regarding CA file, MSVS version, Python and SSL):
`D:\>npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.10.2 node/v10.16.0 win32 x64"

; userconfig D:\Users\dfreire\.npmrc
chromedriver-cdnurl = "https://npm.taobao.org/mirrors/chromedriver"
couchbase-binary-host-mirror = "https://npm.taobao.org/mirrors/couchbase/v{version}"
debug-binary-host-mirror = "https://npm.taobao.org/mirrors/node-inspector"
disturl = "https://npm.taobao.org/dist"
electron-mirror = "https://npm.taobao.org/mirrors/electron/"
flow-bin-binary-host-mirror = "https://npm.taobao.org/mirrors/flow/v"
fse-binary-host-mirror = "https://npm.taobao.org/mirrors/fsevents"
fuse-bindings-binary-host-mirror = "https://npm.taobao.org/mirrors/fuse-bindings/v{version}"
git4win-mirror = "https://npm.taobao.org/mirrors/git-for-windows"
gl-binary-host-mirror = "https://npm.taobao.org/mirrors/gl/v{version}"
grpc-node-binary-host-mirror = "https://npm.taobao.org/mirrors"
hackrf-binary-host-mirror = "https://npm.taobao.org/mirrors/hackrf/v{version}"
leveldown-binary-host-mirror = "https://npm.taobao.org/mirrors/leveldown/v{version}"
leveldown-hyper-binary-host-mirror = "https://npm.taobao.org/mirrors/leveldown-hyper/v{version}"
mknod-binary-host-mirror = "https://npm.taobao.org/mirrors/mknod/v{version}"
node-sqlite3-binary-host-mirror = "https://npm.taobao.org/mirrors"
node-tk5-binary-host-mirror = "https://npm.taobao.org/mirrors/node-tk5/v{version}"
nodegit-binary-host-mirror = "https://npm.taobao.org/mirrors/nodegit/v{version}/"
npm_config_electron_mirror = "https://github.com/electron/electron/releases/download/"
operadriver-cdnurl = "https://npm.taobao.org/mirrors/operadriver"
phantomjs-cdnurl = "https://npm.taobao.org/mirrors/phantomjs"
prefix = "D:\\Users\\dfreire\\AppData\\Roaming\\npm"
profiler-binary-host-mirror = "https://npm.taobao.org/mirrors/node-inspector/"
puppeteer-download-host = "https://npm.taobao.org/mirrors"
python = "D:\\Users\\dfreire\\.windows-build-tools\\python27\\python.exe"
python-mirror = "https://npm.taobao.org/mirrors/python"
rabin-binary-host-mirror = "https://npm.taobao.org/mirrors/rabin/v{version}"
registry = "https://registry.npmjs.org/"
sass-binary-site = "https://npm.taobao.org/mirrors/node-sass"
sodium-prebuilt-binary-host-mirror = "https://npm.taobao.org/mirrors/sodium-prebuilt/v{version}"
sqlite3-binary-site = "https://npm.taobao.org/mirrors/sqlite3"
strict-ssl = false
utf-8-validate-binary-host-mirror = "https://npm.taobao.org/mirrors/utf-8-validate/v{version}"
utp-native-binary-host-mirror = "https://npm.taobao.org/mirrors/utp-native/v{version}"
zmq-prebuilt-binary-host-mirror = "https://npm.taobao.org/mirrors/zmq-prebuilt/v{version}"

; globalconfig D:\Users\dfreire\AppData\Roaming\npm\etc\npmrc
cafile = "D:\\dev\\projetos\\ngx-materialize\\proxymwg.pem"
msvs_version = "2015"
python = "D:\\Users\\dfreire\\.windows-build-tools\\python27\\python.exe"
strict-ssl = false

; builtin config undefined
prefix = "D:\\Users\\dfreire\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\
; HOME = D:\Users\dfreire
; "npm config ls -l" to show all defaults.`

- Steps to reproduce:
`npm init
npm install electron --save-dev`

The same problem ocurred using angular-cli:
`git clone https://github.com/maximegris/angular-electron.git
npm install`

And also using Ionic & Electron.

Thanks for helping!

**Comment by malept** [comment]
You set `electron-mirror` in your NPM config but not `electron-custom-dir` as per https://github.com/electron/get/issues/150#issuecomment-597928937.

**Comment by kaosnoff** [comment]
As I said before, I've never explicitly set electron_mirror to taobao (nor the other mirrors in my npm config). I really didn't even know how to do it.

Anyways, thanks for your help and patience.

Just to document what really fixed the problem for me, it was deleting the electron-mirror setting, changing it back to default:

`npm config delete electron-mirror`

**Comment by malept** [comment]
It was whatever created the entries in `D:\Users\dfreire.npmrc` for you. If you know what set all those mirrors for you (not just Electron), you can file a bug with that tool to add `electron-custom-dir` to that litany of config values.
