### ISSUE TITLE
What license should I mention this repository under 

### ISSUE THREAD

**Issue by AtiqGauri** [electron/get#164]
I am build an electron app and this repository is transitive dependency of my project. 

### ISSUE:
There is no license attached to this repository and nothing mentioned in readme document.

### SOLUTION:
can you add or guide me about license formalities of this repository

**Comment by malept** [comment]
The license is specified in the package metadata:
https://github.com/electron/get/blob/9034cc46cb54fabd11d6e540b5093dbbcc7c3a42/package.json#L9

**Comment by RobertBorg** [comment]
I don't think you've actually applied the MIT license unless u properly add the LICENSE file or at the very least somewhere have a license somewhere with the copyright notice.

In order for me to comply with the license you claim to be under i must now reproduce a copyright notice that does not exist which is really hard.

Please add a LICENSE file.
