### ISSUE TITLE
why use NPM_CONFIG?

### ISSUE THREAD

**Issue by yanguoyu** [electron/get#169]
![image](https://user-images.githubusercontent.com/12881040/92357614-b963f180-f11a-11ea-948b-a5074623de3b.png)
if i set .npmrc ELECTRON_MIRROR, the process.env has npm_config_ELECTRON_MIRROR, so i set electron_mirror.
i want know when process.env has NPM_CONFIG_.

**Comment by MarshallOfSound** [comment]
Environment variables are case sensitive on some versions of node / npm.  This is for backwards compatibility with old releases.
