### ISSUE TITLE
npm install is failing intermittently with 404 error.

### ISSUE THREAD

**Issue by shubhamyelekar** [electron/get#171]
Operating System: Windows Server 2012

When I run npm install, it fails sometimes with the error

```
[exec] > electron@10.1.1 postinstall <path>\node_modules\electron
[exec] > node install.js

HTTPError: Response code 404 (Not Found) for http://<custom_repo>/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip
```

I tried the same thing with the default npm repo as well, the URL https://registry.npmjs.org/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip returns "resource not found error".
`{"code":"ResourceNotFound","message":"/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip does not exist"}`

What is the correct URL for this and is there any way to tell @electron/get to download from that URL? Also, it is not clear why this happens intermittently. 70% of the time it works as expected.

Electron v10.1.1
Electron packager v15.0.0

**Comment by malept** [comment]
I suspect your electron mirror options aren't set correctly. By default Electron is downloaded from GitHub Releases.
