### ISSUE TITLE
Has the cache been changed?

### ISSUE THREAD

**Issue by YF1999** [electron/get#188]
The installer of electron@11.2.1 has been cached into `C:\Users\YF\AppData\Local\electron\Cache\8929302e09b6a213ccd7c6f1e48fb14c4053144515fdb12d25ad645abcb59af2`, not `C:\Users\YF\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv11.2.1electron-v11.2.1-win32-x64.zip`, is it by design?

**Comment by malept** [comment]
Yes, this changed in [1.12.4](https://github.com/electron/get/releases/tag/v1.12.4).

**Comment by YF1999** [comment]
> Yes, this changed in [1.12.4](https://github.com/electron/get/releases/tag/v1.12.4).

Thanks for your answer.
Please change the document to let us know how the cache directory has been changed.

**Comment by malept** [comment]
Which document?

**Comment by YF1999** [comment]
I mean, maybe you could change readme to let us know that the cache folder has been changed from `$ESCAPED_URL` to `sha256(dirname($URL))`.
Somebody, like me, need to manage the cache manually to speed up the first installation of a new electron version.

**Comment by malept** [comment]
Changes are generally communicated in the release notes (which I linked), not the README.
