### ISSUE TITLE
Expose Functionality to Clear/Delete Versions From Cache

### ISSUE THREAD

**Issue by dsanders11** [electron/get#209]
Would be useful if this library exposed functions which could be used to:

* Clear the entire cache
* Delete specific versions from the cache

Since Electron Fiddle uses this project to download versions, the delete functionality in Fiddle only deletes some of what's downloaded to disk, since the cache here in the `get` project lives on.

So ideally this project would expose a function that Fiddle could use to delete a cached version from disk so that delete in Fiddle truly means delete, instead of leaving gigs of cached versions behind. For someone with limited disk space (500 GB), this is a noticeable pain point.

**Comment by MarshallOfSound** [comment]
I think it would be better if `get` just allowed fiddle to say "bypassCache: true".  Exposing cache related API surface doesn't sound fun as we mess with cache related things all the time.  Just saying "plz no cache I'll do it myself" seems more reasonable

**Comment by dsanders11** [comment]
@MarshallOfSound, fair point. I was just thinking clear/delete wouldn't get too far into the weeds, but you're right, any new API surface is a new maintenance burden.

Just my 2 cents, but maybe `noCache` or `dontCache` could work as the option name, `bypassCache` could be confusingly close to `force` since `force` "bypasses" the cache and downloads the file again, but still caches the result.
