### ISSUE TITLE
GLOBAL_AGENT.HTTP_PROXY configuration value: URL protocol must be http:

### ISSUE THREAD

**Issue by zzz08900** [electron/get#215]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  *  14.2.1, 15.4.0
* **Electron Version:**
  *  17.1.2
* **Operating System:**
  *  Ubuntu 20.04 x64
* **Last Known Working Electron Packager version:**
  *  13.1.1

### Expected Behavior

Building Win32 packages from my Ubuntu machine (with Wine installed) using `electron-packager . --platform=win32 --out=./builds`
Should get me Win32 artifacts in the ./builds folder.

### Actual Behavior

Building Win32 packages from my Ubuntu machine (with Wine installed) using `electron-packager . --platform=win32 --out=./builds`
results in error message: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".
The error originated from global-agent which is an optional dependency of @electron/get. 

### To Reproduce

1. find a Linux machine, create an empty nodeJS project, setup a barebone package.json
2. put the following in package.json 
  "devDependencies": {
    "electron": "^17.1.2",
    "electron-devtools-installer": "^3.2.0",
    "electron-packager": "^15.4.0"
  }
3. try `npx electron-packager . --platform=win32 --out=./builds`, you shoule see the error message

### Additional Information

Debug info attached below:
  electron-packager Electron Packager 15.4.0
  electron-packager Node v14.17.5
  electron-packager Host Operating system: linux 5.13.0-30-generic (x64) +0ms
  electron-packager Packager Options: {"_":["."],"platform":"win32","out":"./builds","deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","protocols":[]} +2ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Requiring author in package.json, as CompanyName was not specified for win32metadata +0ms
  electron-packager Inferring application name from name in {omitted}/package.json +13ms
  electron-packager Inferring appVersion from version in {omitted}/package.json +0ms
  electron-packager Inferring target Electron version from electron in {omitted}/package.json +5ms
  electron-packager Application name: {omitted} +18ms
  electron-packager Target Electron version: 17.1.2 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"17.1.2","artifactName":"electron"} +0ms
Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".

**Comment by malept** [comment]
@zzz08900 What is the value of the `HTTP_PROXY` environment variable? Or, I guess, `GLOBAL_AGENT.HTTP_PROXY`?

This appears to be a regression from #214 

CC: @BlackHole1

**Comment by BlackHole1** [comment]
I've found the problem, please wait. I will submit a PR later

**Comment by NixerSo5** [comment]
"electron": "^26.2.1"
Operating System:
Windows11 23545.1000
RequestError: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".
it still  not work   and   i  don`t know  how  to  fix it

**Comment by BlacknoSheep** [comment]
@NixerSo5 I encountered the same issue when installing the alpha version and the nightly version. It seems that only the stable version has fixed this bug. My solution is：
```powershell
$env:ELECTRON_GET_USE_PROXY=1
$env:GLOBAL_AGENT_HTTP_PROXY="http://127.0.0.1:7890"
# Don't chang GLOBAL_AGENT_HTTPS_PROXY
```
However, it still took me 40 minutes to install electron@v28.0.0-alpha.2. (While installing the stable version only took me a few seconds.

**Comment by siluo2000** [comment]
Here's my solution, maybe it will work for you guys: <https://cloud.tencent.com/developer/article/2369773>

**Comment by bhumpherys** [comment]
I am getting this error again trying to install v2.0.3, so it seems to come and go periodically. Any chance that we can expect another fix for this one?
