### ISSUE TITLE
[Feature Request]: auto proxy

### ISSUE THREAD

**Issue by BlackHole1** [electron/get#217]
If `HTTP(S)_PROXY` / `GLOBAL_AGENT_HTTP(S)_PROXY` is present in the environment variable, the proxy is automatically set.

Behaves like: `curl` / `wget`.

> I'd be willing to implement this feature

**Comment by BlackHole1** [comment]
@electron/wg-ecosystem

**Comment by malept** [comment]
Currently the tools/apps that use `@electron/get` are expected to set that up themselves. 

https://github.com/electron/get/blob/c99de4bd1f8c21e4da98a4b8ac37012530e99c50/src/proxy.ts#L6-L31

See also: https://github.com/electron/get/pull/118

**Comment by paztis** [comment]
why is the electron main package postinstall "install.js" script is not configuring it ?
I've add a log in this initializeProxy function and never see it pass during the postinstall of electron
