### ISSUE TITLE
Upgrade `got` dependency to 12.5.0 or higher to fix security vulnerability

### ISSUE THREAD

**Issue by nabchar** [electron/get#244]
Snyk lists `http-cache-semantics` as having a Regular Expression Denial of Service (ReDoS) security vulnerability for any versions prior to `4.1.1`. [Read here for more info.](https://security.snyk.io/vuln/SNYK-JS-HTTPCACHESEMANTICS-3248783)

In this package, the [dependency](https://github.com/electron/get/blob/main/package.json#L32) on `"got": "^11.8.5"` internally has a [dependency](https://github.com/sindresorhus/got/blob/v11.8.6/package.json#L51) on `"cacheable-request": "^7.0.2"`, which in turn has a [dependency](https://github.com/jaredwray/cacheable-request/blob/v7.0.2/package.json#L34) on `"http-cache-semantics": "^4.0.0"` -- which is tied to a minor version that has the security vulnerability mentioned above.

**Comment by erickzhao** [comment]
Duplicate of https://github.com/electron/get/issues/242

`"http-cache-semantics": "^4.0.0"` is _not_ tied to the vulnerable version. 4.1.1 is compliant with `^4.0.0`.
