### ISSUE TITLE
Missing LICENSE file in the repo of ver 1.12.2

### ISSUE THREAD

**Issue by itsuki-murata** [electron/get#296]
Currently I'm using @electron/get ver 1.12.2, but can't find a LICENSE file in the repo of ver 1.12.2.
Could you add the LICENSE file in the repo of ver 1.12.2?
Or is it possible to use the LICENSE file of the latest version as the license for ver 1.12.2?
Thanks in advance.

**Comment by itsuki-murata** [comment]
I'm also using electron-download ver 1.4.1, but can't find a LICENSE file in the repo of ver 1.4.1.
Could you add the LICENSE file for electron-download ver 1.4.1?
Thanks in advance.

**Comment by erickzhao** [comment]
Hi, I would recommend upgrading your `@electron/get` dependency in your lockfile. It should be available as of v1.12.3: https://github.com/electron/get/pull/172
